[package]
name = "lean-lib"
version = "0.1"
lean_version = "3.4.1"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "b3fc801318bdb28121f3e3974b287cdcf4d63032"}
mathlib-nursery = {git = "https://github.com/leanprover-community/mathlib-nursery", rev = "0f1384ae50c1c5161af024926330e8baa9424d45"}
