[package]
name = "lean-lib"
version = "0.1"
lean_version = "3.4.2"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "tags/snapshot-2019-10"}
mathlib-nursery = {git = "https://github.com/leanprover-community/mathlib-nursery", rev = "tags/snapshot-2019-10"}
